name: deploy

on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Build plugin.
        run: |
          SP_VERSION=`printf "%s\n" "${GITHUB_REF##*/}"`
          SP_REPOSITORY=`printf "%s\n" "${GITHUB_REPOSITORY##*/}"`
          echo "::set-env name=SP_VERSION::${SP_VERSION}"
          echo "::set-env name=SP_REPOSITORY::${SP_REPOSITORY}"

          sed -i s/0.0.0/${SP_VERSION}/g sitepilot.php

          composer install --no-dev

          npm install
          npm run production

      - name: Commit file to release.
        run: |
          git config --global user.name 'Sitepilot'
          git config --global user.email 'sitepilot@users.noreply.github.com'
          git commit -am "Bump version"
          git push
        if: github.event.release

      - name: Upload zip to release.
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ../${{ env.SP_REPOSITORY }}.zip
          asset_name: ${{ env.SP_REPOSITORY }}.zip
          asset_content_type: application/zip
        if: github.event.release
