name: deploy

on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - run: |
          composer install --no-progress --no-dev
          npm run production

          VERSION=`printf "%s\n" "${GITHUB_REF##*/v}"`
          sed -i "s/[0-9]*\.[0-9]*\.[0-9]*\-dev/${VERSION}/g" sitepilot.php

          zip -r ./sitepilot.zip ./ -x '*.git*' -x '*.github*' -x '*node_modules*'

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sitepilot.zip
          asset_name: sitepilot.zip
          asset_content_type: application/zip
        if: github.event.release

      - uses: sitepilot/action-deploy@main
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: rclone copy sitepilot.zip remote:/sites/update-hrg7/public/public/v1/packages/sitepilot.zip -v
        if: github.event.release
