name: build-plugin

on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build plugin.
        run: |
          composer install --no-dev

          npm install
          npm run production

          rm -rf .git
          rm -rf node_modules

          zip -r ${{ github.workspace }}/../sitepilot.zip ./

      - uses: actions/upload-artifact@v2
        with:
          name: sitepilot
          path: ${{ github.workspace }}/../sitepilot.zip

      - name: "Deploy plugin to SFTP and release."
        uses: docker://ghcr.io/sitepilot/wp-sftp-deploy:latest
        env:
          SP_SFTP_KEY: ${{ secrets.WP_UPDATE_SFTP_KEY }}
          SP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SP_VERSION_FILE: "sitepilot.php"
        if: github.event.release
