name: deploy-private

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Private Release
        run: |
          composer install --no-dev
          npm install
          npm run production
          curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H 'Accept: application/vnd.github.v3.raw' -L https://gist.githubusercontent.com/nick-jansen/194415323045e634e38082d087fc677f/raw -o classes/Defaults.php
      - uses: docker://sitepilot/wp-sftp-deploy:latest
        env:
          SP_SFTP_KEY: ${{ secrets.SP_SFTP_KEY }}
