name: deploy

on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build plugin.
        run: |
          SP_REPOSITORY=`printf "%s\n" "${GITHUB_REPOSITORY##*/}"`
          echo "::set-env name=SP_REPOSITORY::${SP_REPOSITORY}"

          sed -i s/-{dev}//g sitepilot.php

          composer install --no-dev

          npm install
          npm run production

      - name: Upload zip to release.
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ../${{ env.SP_REPOSITORY }}.zip
          asset_name: ${{ env.SP_REPOSITORY }}.zip
          asset_content_type: application/zip
        if: github.event.release
