name: deploy-public

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Public Release
        run: |
          composer install --no-dev
          npm install
          npm run production
          sed -i s/{{SP_SLACK_WEBHOOK}}//g classes/Modules/Support.php
          sed -i s/{{SP_WHITELISTED_IPS}}//g classes/Modules/Support.php
          sed -i s/{{SP_SUPPORT_SCRIPT}}//g classes/Modules/Support.php
      - uses: docker://sitepilot/wp-ftp-deploy:latest
        env:
          GITHUB_TOKEN: ${{ secrets.SP_GITHUB_TOKEN }}
